title: GCDC Maturity Model WG
description: An open space to work on the GCDC Data Maturity Model
theme: just-the-docs

url: https://just-the-docs.github.io

aux_links:
  CSPS: https://csps-efpc.gc.ca
